from enum import Enum

class Intent(str, Enum):
    ORDER_TRACKING = "ORDER_TRACKING"
    ORDER_STATUS = "ORDER_STATUS"
    ORDER_HISTORY = "ORDER_HISTORY"
    PRODUCT_LOOKUP = "PRODUCT_LOOKUP"
    INVENTORY_CHECK = "INVENTORY_CHECK"
    CREATE_ORDER = "CREATE_ORDER"
    CANCEL_ORDER = "CANCEL_ORDER"
    INVOICE_REQUEST = "INVOICE_REQUEST"
    STORE_HOURS = "STORE_HOURS"
    HELP = "HELP"
    GREETING = "GREETING"
    CATALOG = "CATALOG"
    MENU_SELECTION = "MENU_SELECTION"
    UNKNOWN = "UNKNOWN"
